apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-svc
  namespace: insuretech
  labels:
    app: scaletestapp
spec:
  selector:
    app: scaletestapp
  ports:
  - name: http
    port: 80
    targetPort: 8080